# Generated by Django 3.2 on 2022-06-28 16:55

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0008_auto_20220207_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='importance',
            field=models.PositiveSmallIntegerField(default=100),
        ),
    ]
