# Generated by Django 3.2 on 2022-07-02 09:10

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0009_auto_20220629_1408'),
    ]

    operations = [

        migrations.AddField(
            model_name='link',
            name='is_bookmark',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),

    ]
